# Generated by Django 4.2.10 on 2024-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('yearly_avg_view', models.IntegerField()),
                ('frequentflyer', models.BooleanField()),
                ('preferred_device', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop')], max_length=10)),
                ('yearly_avg_outstation_checkins', models.IntegerField()),
                ('annual_income_class', models.CharField(choices=[('Average', 'Average'), ('High', 'High'), ('Low', 'Low')], max_length=10)),
                ('member_in_family', models.IntegerField()),
                ('booking_hotel', models.BooleanField()),
                ('preferred_location_type', models.CharField(max_length=200)),
                ('working_flag', models.BooleanField()),
                ('travelling_rating', models.IntegerField()),
            ],
        ),
    ]
